version: '3'

services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    ports:
    - "27000:27017"
  reactive-app:
    image: reactive
    container_name: "reactive-app"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/reactive-app
    ports:
      - "8701:8701"